### ISSUE TITLE
Is <profile> for windowsExtension needed?

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-microprofile-opentracing#74]
Check if for windowsExtension is needed for this guide, if not remove.

**Comment by gkwan-ibm** [comment]
be used at the inventory/pom.xml for the mvn command

**Comment by yeekangc** [comment]
I would like to understand why we need it besides what we use it for.

**Comment by gkwan-ibm** [comment]
In multiple modules, the system runs the test by itself to start server, run test, and stop server. When the inventory runs the test, it cannot only start its server but as well as the system server. To make the system server run, additional start and stop server mvn commands are added in the pom.xml. To invoke mvn, the windowsExtension is used to call mvn.cmd. Actually, it is not necessary, Windows should be able to call `mvn` instead of `mvn.cmd` explicitly.

**Comment by gkwan-ibm** [comment]
In current implementation, `windowsExtension` is necesssary. Let re-investigate it when switch to use dev mode and liberty maven plugin 3.0.

**Comment by gkwan-ibm** [comment]
https://github.com/OpenLiberty/guides-common/issues/360

**Comment by gkwan-ibm** [comment]
close
- this guide is stabilized, i.e. not change anymore
- will direct users to a new guide for mp-opentelemetry
